application: bitsbangapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /u/.*
  script: bitsable/bitsbang/user/main.py

- url: /signup
  script: bitsable/bitsbang/user/main.py
  
- url: /signin
  script: bitsable/bitsbang/user/main.py
  
- url: /signout
  script: bitsable/bitsbang/user/main.py

- url: /spam/.*
  script: bitsable/bitsbang/spam/main.py
  
- url: /spam
  script: bitsable/bitsbang/spam/main.py

- url: .*
  script: main.py
